config/routes.rb
Su21::Application.routes.draw do
  devise_for :users, :skip => :registrations
  root 'static_pages#home'

  namespace :admin do
    match '/', to: 'dashboard#dashboard', via: 'get'
    resources :lessons
    resources :posts
    resources :settings, only:[:index, :edit, :update]
    match '/settings/vk/sign_up',  to: 'vk_sessions#new', via: 'get'
    match '/settings/vk/callback', to: 'vk_sessions#callback', via: 'get'
    match '/settings/vk/destroy',  to: 'vk_sessions#destroy', via: 'delete'
  end

  match 'day',  to: 'lessons#day',  via: 'get'
  match 'week', to: 'lessons#week', via: 'get'
  match 'vk_posts', to: 'posts#vk_posts', via: 'get', constraints: { format: /(js|json|mobile)/ }

  resources :posts, only:[:index, :show]
  match 'posts_preview', to: 'posts#posts_preview', via: 'get', constraints: { format: /(js|json)/ }

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include LessonsHelper

	def home
		day_info = get_day_info
		@current_week = day_info[0]
		@current_day = day_info[1]
		periodicity = day_info[2]
		@when_lessons = "Сегодня"
		if Time.now.hour >= 18
			if @current_day >= 6
				@when_lessons = "В понедельник"
				@current_day = 1
				@current_week += 1
				periodicity = @current_week % 2 == 0 ? 2 : 1
			else 
				@when_lessons = "Завтра"
				@current_day += 1
			end
		end
		@lessons = Lesson.where("day = ? AND start_week <= ? AND end_week >= ? AND (periodicity = ? OR periodicity = 3)", 
											@current_day, 
											@current_week, 
											@current_week,
											periodicity)
											.order(number: :asc)
		@posts = Post.order(updated_at: :desc).limit(3)
		@count = Post.count
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_lessons.html.slim
h5 
	= link_to day_path(week: @current_week, day: @current_day) do
		= @when_lessons
hr
h5
	= "С #{to_time(@lessons[0].number).split("-")[0]}"
table
	- @lessons.each do |lesson|
		tr
			td 
				= lesson.name
			td 
				span.glyphicon.glyphicon-time
				= to_time(lesson.number).split("-")[0]
			td 
				span.glyphicon.glyphicon-map-marker
				= lesson.classroom
			td
				span.glyphicon.glyphicon-pencil
				= to_type lesson.form
h5
	= "До #{to_time(@lessons.last.number).split("-")[1]}"

app/views/static_pages/_posts.html.slim
h5 
	= link_to "Посты", posts_path
#list-group-wrapper
	.list-group
		- @posts.each do |post|
			.list-group-item
				h3 
					= link_to post.title, post_path(post)
				p = truncate(post.text.gsub(/(-+)|(`+)|(#+)/," ") , length: 80)
				p
					span.glyphicon.glyphicon-time 
					= "#{time_ago_in_words(post.updated_at)} ago"
				= render "shared/manage_links", edit_path: edit_admin_post_path(post), delete_path: admin_post_path(post), short:true
#posts-nav
	div class="btn-group center"
		- if params[:offset].nil? || params[:offset].to_i == 0
			= link_to posts_preview_path(offset: params[:offset].to_i - 3), class: "btn btn-default", disabled: "disabled" do
				span.glyphicon.glyphicon-chevron-left
		- else
			= link_to posts_preview_path(offset: params[:offset].to_i - 3), remote: true, class: "btn btn-default" do
				span.glyphicon.glyphicon-chevron-left
		- if ((params[:offset] && (params[:offset].to_i / 3 + 1) * 3 > @count) || 3 >= @count)
			= link_to posts_preview_path(offset: params[:offset].to_i + 3), class: "btn btn-default", disabled: "disabled" do
				span.glyphicon.glyphicon-chevron-right
		- else
			= link_to posts_preview_path(offset: params[:offset].to_i + 3), remote: true, class: "btn btn-default" do
				span.glyphicon.glyphicon-chevron-right

app/views/static_pages/_vk_posts.html.slim
h5 
	a href="#" Вк feed
#list-group-wrapper
	#fa-spin-wrapper
		i.fa.fa-spinner.fa-spin.fa-2x
	.list-group
		- @posts.each do |post|
			a href="https://vk.com/su_21?w=wall-42551290_#{post.id}" class="list-group-item" target="blank"
				div class="media"
					div.pull-left
						img.img-circle src="#{post.user.photo}"
					div class="media-body"
						p 
							= truncate(post.text.gsub(/<\/?br>/, " "), length: 60)	
						p 
							span.glyphicon.glyphicon-time 
							= time_ago_in_words(Time.at(post.date)) + " ago"
							- if post.attachments
								i.fa.fa-file-o
								= attachment_type_to_word post.attachments[0].type
							i.fa.fa-comment-o
							= post.comments["count"]

#posts-nav								
	div class="btn-group"
		- if params[:offset].nil? || params[:offset].to_i == 0
			= link_to vk_posts_path(offset: params[:offset].to_i - 3), class: "btn btn-default", disabled: "disabled" do
				span.glyphicon.glyphicon-chevron-left
		- else
			= link_to vk_posts_path(offset: params[:offset].to_i - 3), remote: true, class: "btn btn-default" do
				span.glyphicon.glyphicon-chevron-left
		= link_to vk_posts_path(offset: params[:offset].to_i + 3), remote: true, class: "btn btn-default" do
			span.glyphicon.glyphicon-chevron-right
		
			
		
			

app/views/static_pages/home.html.slim
- content_for(:title, "Главная")
.container#home
	.row
		- if @lessons.empty?
			.col-md-4.preview.lesson-preview.bgi
				= render "shared/time", url: day_path(week: 1, day: 1)
		- else
			.col-md-4.preview.lesson-preview
				= render "lessons"
		- if Settings.vk_id
			.col-md-4.preview.vk-preview
				h5 
					a href="#" Вк feed
				#list-group-wrapper
					#fa-spin-wrapper
						i.fa.fa-spinner.fa-spin.fa-2x
				#posts-nav
					div class="btn-group center"
						= link_to vk_posts_path, class: "btn btn-default", disabled: "disabled" do
							span.glyphicon.glyphicon-chevron-left
						= link_to vk_posts_path, class: "btn btn-default", disabled: "disabled" do
							span.glyphicon.glyphicon-chevron-right
		- unless @posts.empty?
			.col-md-4.preview.posts-preview
				= render "posts"

app/views/static_pages/home.mobile.slim
- content_for(:title, "Главная")
- content_for(:header) do
	h1 class="title"
		| Привет!

.content-padded#home-page
	div
		p.center
			i class="fa fa-arrow-up fa-2x"
		h4.center.fw300 Тут будут находиться элементы управления во вкладке, которую ты выбрал
	#home-page-bottom
		h4.center.fw300 Просто нажмите на одну из вкладок
		p.center
			i class="fa fa-arrow-down fa-2x"

= render "shared/mobile_bar_tab"