config/routes.rb
Su21::Application.routes.draw do
  devise_for :users, :skip => :registrations
  root 'static_pages#home'

  namespace :admin do
    match '/', to: 'dashboard#dashboard', via: 'get'
    resources :lessons
    resources :posts
    resources :settings, only:[:index, :edit, :update]
    match '/settings/vk/sign_up',  to: 'vk_sessions#new', via: 'get'
    match '/settings/vk/callback', to: 'vk_sessions#callback', via: 'get'
    match '/settings/vk/destroy',  to: 'vk_sessions#destroy', via: 'delete'
  end

  match 'day',  to: 'lessons#day',  via: 'get'
  match 'week', to: 'lessons#week', via: 'get'
  match 'vk_posts', to: 'posts#vk_posts', via: 'get', constraints: { format: /(js|json|mobile)/ }

  resources :posts, only:[:index, :show]
  match 'posts_preview', to: 'posts#posts_preview', via: 'get', constraints: { format: /(js|json)/ }

end

app/views/shared/_errors.html.slim
- if object.errors.any?
	div.panel.panel-danger
		div.panel-heading 
			= pluralize(object.errors.count, "error")
		div.panel-body
			ul
				- object.errors.full_messages.each do |message|
					li = message

app/views/shared/_manage_links.html.slim
#manage
	= link_to edit_path do
		span.glyphicon.glyphicon-pencil
		= "Редактировать" unless defined? short 
	= link_to delete_path, method: :delete do
		span.glyphicon.glyphicon-remove
		= "Удалить" unless defined? short

app/views/shared/_mobile_bar_tab.mobile.slim
nav class="bar bar-tab"
	= link_to day_path, class: "tab-item #{'active' if params[:action] == 'day'}", "data-transition"=>"fade" do
		span class="icon fa fa-list-alt"
		span class="tab-label" 
			| День
	= link_to week_path, class: "tab-item #{'active' if params[:action] == 'week'}", "data-transition"=>"fade" do
		span class="icon fa fa-table"
		span class="tab-label" 
			| Неделя
	= link_to posts_path, class: "tab-item #{'active' if params[:action] == 'index' || params[:controller] == 'posts'}", "data-transition"=>"fade" do
		span class="icon icon-pages"
		span class="tab-label" 
			| Посты

app/views/shared/_post.html.slim
article
	div.center
		h1 = @post.title
		p.meta 
				span.glyphicon.glyphicon-time
				= "#{time_ago_in_words(@post.updated_at)} ago"
		- if signed_in?
			= render "shared/manage_links", edit_path: edit_admin_post_path(@post), delete_path: admin_post_path(@post)
	hr
	p = markdown @post.text

app/views/shared/_time.html.slim
div#time-wrapper
	h3 До начала семестра осталось
	div id="time" data-date="#{Settings.date}"
	- unless url && url.empty?
		h3
			= link_to "Что нас ждет", url