config/routes.rb
Su21::Application.routes.draw do
  devise_for :users, :skip => :registrations
  root 'static_pages#home'

  namespace :admin do
    match '/', to: 'dashboard#dashboard', via: 'get'
    resources :lessons
    resources :posts
    resources :settings, only:[:index, :edit, :update]
    match '/settings/vk/sign_up',  to: 'vk_sessions#new', via: 'get'
    match '/settings/vk/callback', to: 'vk_sessions#callback', via: 'get'
    match '/settings/vk/destroy',  to: 'vk_sessions#destroy', via: 'delete'
  end

  match 'day',  to: 'lessons#day',  via: 'get'
  match 'week', to: 'lessons#week', via: 'get'
  match 'vk_posts', to: 'posts#vk_posts', via: 'get', constraints: { format: /(js|json|mobile)/ }

  resources :posts, only:[:index, :show]
  match 'posts_preview', to: 'posts#posts_preview', via: 'get', constraints: { format: /(js|json)/ }

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	VALID_CLASSROOM_REGEX = /\A^\d{3}(\/\d{1}|\/\d{1}\/\d{1})$\z/i
  # default_scope -> { order('day ASC, number ASC') }
	validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :form, presence: true, numericality: { only_integer: true, 
  																								 greater_than_or_equal_to: 1,
  																								 less_than_or_equal_to: 3 }
  validates :number, presence: true, numericality: { only_integer: true, 
  																								 greater_than_or_equal_to: 1,
  																								 less_than_or_equal_to: 5 } 
  validates :classroom, presence: true, length: {minimum: 3, maximum: 10}, format: {with: VALID_CLASSROOM_REGEX}
  validates :day, presence: true, numericality: { only_integer: true, 
  																								 greater_than_or_equal_to: 1,
  																								 less_than_or_equal_to: 7 }
  validates :start_week, presence: true, numericality: { only_integer: true, 
  																								 greater_than_or_equal_to: 1,
  																								 less_than_or_equal_to: 18 }
  validates :end_week, presence: true, numericality: { only_integer: true, 
  																								 greater_than_or_equal_to: 1,
  																								 less_than_or_equal_to: 18 }
                                                   
  validates :periodicity, presence: true, numericality: { only_integer: true, 
                                                          greater_than_or_equal_to: 1,
                                                          less_than_or_equal_to: 3 }  


  def self.search(search)
    if search 
      where 'name LIKE ?', "%#{search}%" 
    else
      scoped
    end
  end

  def self.get_by(opts = {})
    if opts[:day].blank?
      where("start_week <= ? AND end_week >= ? AND (periodicity = ? OR periodicity = 3)",
            opts[:week],
            opts[:week],
            opts[:periodicity]).order(number: :asc)
    else
      where("day = ? AND start_week <= ? AND end_week >= ? AND (periodicity = ? OR periodicity = 3)", 
            opts[:day], 
            opts[:week], 
            opts[:week],
            opts[:periodicity]).order(number: :asc)
    end
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::AdminController
  helper_method :sort_column, :sort_direction

	def index 
    @lessons = Lesson.search(params[:search]).order(sort_column + " " + sort_direction).paginate(per_page: 10, page: params[:page])
	end 

	def new 
		@lesson = Lesson.new
	end

	def create
		@lesson = Lesson.new(lesson_params)
  	if @lesson.save
  		flash[:success] = "Пара создана"
  		redirect_to admin_lessons_path
  	else
  		render 'new'
  	end
	end

  def edit 
    @lesson = Lesson.find(params[:id])
  end

  def update 
    @lesson = Lesson.find(params[:id])
    if @lesson.update_attributes(lesson_params)
      flash[:success] = "Занятие обновлено"
      redirect_to admin_lessons_path
    else
      render 'edit'
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id]).destroy
    respond_to do |format|
      format.html do
        flash[:success] = "Пара удалена"
        redirect_to admin_lessons_path
      end
      format.js
    end
  end

	private
    def lesson_params
      params.require(:lesson).permit(:name,
      															 :form,
      															 :number,
      															 :classroom,
      															 :day,
      															 :start_week,
      															 :end_week,
      															 :periodicity)
    end

    def sort_column
      Lesson.column_names.include?(params[:sort]) ? params[:sort] : "day"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	include LessonsHelper
	before_action :set_day_info
	
	def day
		@lessons = LessonsDecorator.decorate(Lesson.get_by(day: @date_info.day, week: @date_info.week, periodicity: @date_info.periodicity),
																				 context: {week: @date_info.week, day: @date_info.day})
		# logger.debug @date_info.date.strftime("%e %b")
	end

	def week
		@lessons = Lesson.get_by(week: @current_week, periodicity: @periodicity)
	end

	private
		def set_day_info
			@date_info = DateInfo.new(params[:week], params[:day])
		end
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
	def what_week?
    point_week = Settings.date.to_datetime.strftime("%W").to_i
    current_week = Time.now.strftime("%W").to_i
    current_week - point_week + 1
  end

  def get_day_info
    week = params[:week].blank? ? what_week? : params[:week].to_i
    day = if params[:day].blank?
      Time.now.wday == 0 ? 7 : Time.now.wday
    else 
      params[:day].to_i
    end
    periodicity = week % 2 == 0 ? 2 : 1
    [week, day, periodicity]
  end
end

app/views/lessons/_day_lesson.html.slim
li class="list-group-item"
	.row
		.col-xs-1
			span class="label"
				= lesson.number
		.col-xs-11
			h3
				= lesson.name
			- if signed_in?
				= render "shared/manage_links", edit_path: edit_admin_lesson_path(lesson), delete_path: admin_lesson_path(lesson), short:true
			p 
				span.glyphicon.glyphicon-time 
				= to_time lesson.number
			p	
				span.glyphicon.glyphicon-map-marker
				| А. 
				= lesson.classroom
			p	
				span.glyphicon.glyphicon-pencil
				= to_type(lesson.form)

app/views/lessons/_day_lessons.html.slim
.center.row.day-nav
	.col-xs-3
		= @lessons.prev_link
	.col-xs-6
		div class="dropdown"
			div id="dropdownMenu1" data-toggle="dropdown" 
				h3.fw300 
					= to_day @date_info.day
					= @date_info.date
					span class="caret"
				h4.fw100 
					= @date_info.week
					|  - Неделя 
			ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1"
				= @lessons.dropdown_links
	.col-xs-3
		= @lessons.next_link
			
- if @date_info.week >= 1 && @date_info.week <= 18
	#list-group-wrapper
		ul class="list-group"
			- 5.times do |i|
				- if lesson = @lessons.find { |lesson| lesson.number == i + 1 }
					= render "day_lesson", lesson: lesson
				- else 
					li class="list-group-item disabled"
						.row
							.col-xs-1
								span class="label"
									= i + 1
							.col-xs-11
								h3
									| Пары нет
								p 
									span.glyphicon.glyphicon-time 
									= to_time i + 1
				- if i == 1
					li.list-group-item.list-group-item-warning.center
						h4.fw300 Обед
- else 
	- if @date_info.week > 18
		ul class="list-group"
			li class="list-group-item disabled"
				h3.miss.center Семестр закончился
	- else
		= render "shared/time", url: day_path(week: 1, day: 1)
		

app/views/lessons/_spacer.mobile.slim
- if @current_week > 18
	.content-padded
		h3.center.fw300 Семестр закончился
- else
	.content-padded
		h3.center.fw300 Еще отдыхаем
		h4.center.fw300 
			| Начинаем с 
			= Settings.date 
		- if page == "day"
			= link_to "Что нас ждет", day_path(week: 1, day: 1), "data-transition"=>"fade", class: "btn btn-block btn-gradient"
		- else
			= link_to "Что нас ждет", week_path(week: 1), "data-transition"=>"fade", class: "btn btn-block btn-gradient"

app/views/lessons/_week_lesson.html.slim
td
	h3
		= lesson.name
	- if signed_in?
		= render "shared/manage_links", edit_path: edit_admin_lesson_path(lesson), delete_path: admin_lesson_path(lesson), short:true
	p
		span.glyphicon.glyphicon-map-marker
		= lesson.classroom
	p
		span.glyphicon.glyphicon-pencil
		= to_type(lesson.form)

app/views/lessons/_week_lessons.html.slim
.row
	.col-xs-12		
		h1.center.fw300 
			= "#{@current_week}-Неделя"
		- if @lessons.any?	
				table.table
					thead
						th
						- 6.times do |i|
							- if @current_day == i + 1 && @current_week == what_week?
								th.current
									= to_day(i + 1)
							- else
								th 
									= to_day(i + 1)
					tbody
						- 5.times do |i|
							tr
								td.legends
									p 
										= i + 1
								- 6.times do |j|
									- if lesson = @lessons.find {|lesson| lesson.number == i+1 && lesson.day == j+1}
										= render "week_lesson", lesson: lesson
									- else 
										td.disabled
											h3 Пары нет
		- else 
			.row
				.col-md-4.col-md-offset-4
					- if @current_week > 18
						ul class="list-group"
							li class="list-group-item disabled"
								h3.miss.center Семестр закончился
					- else
						= render "shared/time", url: week_path(week: 1)
.row 
	.col-xs-12.center
		ul class="pagination"
			- 18.times do |i|
				- if i + 1 == what_week?
					li.active
						= link_to "#{i+1}", week_path(week: i + 1), remote: true;
				- else 
					li
						= link_to "#{i+1}", week_path(week: i + 1), remote: true;
										

app/views/lessons/day.html.slim
- content_for(:title, "День")
.container
	.row
		.col-md-4.col-md-offset-4
			#lessons
				= render "day_lessons"	

app/views/lessons/day.js.erb
$("#spinner").hide();
$('#lessons').html('<%= escape_javascript(render("day_lessons")) %>');
// $(".list-group").fadeIn(400);
$("#time").TimeCircles({
  "animation": "smooth",
  "bg_width": 0.5,
  "fg_width": 0.01,
  "circle_bg_color": "#60686F",
  "time":
    {
    	"Days":
	      {
	      	"text": "Дней",
		      "color": "#ffa500",
		      "show": true
	      },
	    "Hours":
	    	{
	      	"text": "Часов",
	      	"color": "#ffa325",
	      	"show": true
	      },
	    "Minutes":
	      {
	      	"text": "Минут",
	      	"color": "#ffa243",
	      	"show": true
	      },
	    "Seconds":
	      {
	      	"text": "Секунд",
	      	"color": "#ffa169",
	      	"show": false
	      }
    }
});

app/views/lessons/day.mobile.slim
- content_for(:title, "День")
- content_for(:header) do
	= link_to " ", day_path(prev_date(@current_week, @current_day)), class: "icon icon-left-nav pull-left", "data-transition"=>"fade"
	= link_to " ", day_path(next_date(@current_week, @current_day)), class: "icon icon-right-nav pull-right", "data-transition"=>"fade"
	div id="popover" class="popover"
	  ul class="table-view"
    	- (1..7).each do |i|
				li.table-view-cell
					= link_to to_day(i), day_path(week: @current_week, day: i), "data-transition"=>"fade"
	a href="#popover"
	  h1 class="title"
	    = "#{to_day @current_day}, #{@current_week} - Неделя"
	    span class="icon icon-caret"
- if @current_week >= 1 && @current_week <= 18
	ul class="table-view"
		- 5.times do |i|
			- if @lessons.any? { |lesson| lesson.number == i + 1 }
				- lesson = @lessons.find { |lesson| lesson.number == i + 1 }
				li class="table-view-cell row"
					.lesson-number
						.wrapper 
							span = i + 1
					.lesson-content
						= lesson.name
						p
							i.fa.fa-clock-o
							= to_time i + 1
							i.fa.fa-map-marker
							= lesson.classroom
					.lesson-type
						.wrapper
							span class="badge" = to_type lesson.form
			- else 
				li class="table-view-cell row disabled"
					.lesson-number
						.wrapper 
							span = i + 1
					.lesson-content
						| Пары нет
						p
							i.fa.fa-clock-o
							= to_time i + 1
			- if i == 1
				li class="table-view-divider" Обед
- else
	= render "spacer", page:"day"

app/views/lessons/week.html.slim
- content_for(:title, "Неделя")
.container
	#week_lessons
		= render "week_lessons"

app/views/lessons/week.js.erb
$("#spinner").hide();
$('#week_lessons').html('<%= escape_javascript(render("week_lessons")) %>');
$("#time").TimeCircles({
  "animation": "smooth",
  "bg_width": 0.5,
  "fg_width": 0.01,
  "circle_bg_color": "#60686F",
  "time":
    {
    	"Days":
	      {
	      	"text": "Дней",
		      "color": "#ffa500",
		      "show": true
	      },
	    "Hours":
	    	{
	      	"text": "Часов",
	      	"color": "#ffa325",
	      	"show": true
	      },
	    "Minutes":
	      {
	      	"text": "Минут",
	      	"color": "#ffa243",
	      	"show": true
	      },
	    "Seconds":
	      {
	      	"text": "Секунд",
	      	"color": "#ffa169",
	      	"show": false
	      }
    }
});

app/views/lessons/week.mobile.slim
- content_for(:title, "Неделя")
- content_for(:header) do
	= link_to " ", week_path(week: @current_week - 1), class: "icon icon-left-nav pull-left", "data-transition"=>"fade"
	= link_to " ", week_path(week: @current_week + 1), class: "icon icon-right-nav pull-right", "data-transition"=>"fade"
	div id="popover" class="popover"
	  ul class="table-view"
    	- 18.times do |i|
				li.table-view-cell
					= link_to "#{i+1} - Неделя", week_path(week: i + 1), "data-transition"=>"fade"
	a href="#popover"
	  h1 class="title"
	    = "#{@current_week} - Неделя"
	    span class="icon icon-caret"

- if @lessons.any?
	table.table
		thead
			th
			- 6.times do |i|
				- if @current_day == i + 1 && @current_week == what_week?
					th
						span.badge.current = to_day i + 1, :short
				- else
					th 
						span.badge = to_day i + 1, :short
		tbody
			- 5.times do |i|
				tr
					td.legends
						span.badge = i + 1
					- 6.times do |j|
						- if @lessons.any? {|lesson| lesson.number == i+1 && lesson.day == j+1}
							td
							 	- lesson = @lessons.find {|lesson| lesson.number == i+1 && lesson.day == j+1}
								h4 = truncate(lesson.name, length: 4, omission: " ")
								p
									= lesson.classroom
								p
									= to_type lesson.form, :short
						- else 
							td.disabled
							 | Нет
- else 
	= render "spacer", page: "week"