config/routes.rb
Su21::Application.routes.draw do
  devise_for :users, :skip => :registrations
  root 'static_pages#home'

  namespace :admin do
    match '/', to: 'dashboard#dashboard', via: 'get'
    resources :lessons
    resources :posts
    resources :settings, only:[:index, :edit, :update]
    match '/settings/vk/sign_up',  to: 'vk_sessions#new', via: 'get'
    match '/settings/vk/callback', to: 'vk_sessions#callback', via: 'get'
    match '/settings/vk/destroy',  to: 'vk_sessions#destroy', via: 'delete'
  end

  match 'day',  to: 'lessons#day',  via: 'get'
  match 'week', to: 'lessons#week', via: 'get'
  match 'vk_posts', to: 'posts#vk_posts', via: 'get', constraints: { format: /(js|json|mobile)/ }

  resources :posts, only:[:index, :show]
  match 'posts_preview', to: 'posts#posts_preview', via: 'get', constraints: { format: /(js|json)/ }

end

app/views/layouts/_flashes.html.slim
- flash.each do |key, value| 
	div class=["alert", "alert-" + key.to_s] role="alert" 
		button type="button" class="close" data-dismiss="alert" 
			span aria-hidden="true" &times;
		= value

app/views/layouts/_footer.html.slim
footer
	| footer
	

app/views/layouts/_head.html.slim
head
	title
		= full_title(yield(:title))
	meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
	= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
	= javascript_include_tag "application", "data-turbolinks-track" => true 
	= csrf_meta_tags 
	= yield(:head)
	= favicon_link_tag 'favicon.ico'

app/views/layouts/_navbar.html.slim
#nav-wrapper
  div.nav-button.top-button.sb-toggle-left
    i.fa.fa-bars.fa-2x
  = yield(:nav)

app/views/layouts/_slidebar.html.slim
.sb-slidebar.sb-left
	.sb-logo
		h1.lobster.center Timetable
	ul class="nav nav-pills nav-stacked"
		li 
			= link_to "Главная", root_path
		li 
			= link_to "День", day_path
		li 
			= link_to "Неделя", week_path
		li 
			= link_to "Посты", posts_path
		- if signed_in?
			li
				= link_to "Админка", admin_path


	.sb-footer
		a href="http://vk.com/su_21" 
			i class="fa fa-vk fa-lg"
		a href="mailto:su21spbsut@gmail.com?subject=Отправлено с сайта Су-21"
			i class="fa fa-envelope-o fa-lg"
		a href="https://github.com/nitroFamily/su-21"
			i class="fa fa-github fa-lg"
		hr
		p
			= "#{get_day_info[0]}-Неделя, #{to_day(get_day_info[1])}"

/ '<script src="//cdnjs.cloudflare.com/ajax/libs/slidebars/0.9.4/slidebars.js"></script>

app/views/layouts/admin.html.slim
- content_for(:head) do
	= javascript_include_tag "admin/admin"

html
	= render 'layouts/head'
	body
		= render 'layouts/navbar'
		.sb-site#admin
			div.container
				div.row
					div.col-md-12.flashes
						= render 'layouts/flashes'
				div.row
					div.col-md-3
						ul class="nav nav-pills nav-stacked"
						  li class=("active" if params[:controller] == "admin/dashboard")
						  	= link_to "Dashboard", admin_path
						  li class=("active" if params[:controller] == "admin/lessons")
						  	= link_to "Пары", admin_lessons_path
						  li class=("active" if params[:controller] == "admin/posts")
						  	= link_to "Посты", admin_posts_path
						  li class=("active" if params[:controller] == "admin/settings")
						  	= link_to "Настройки", admin_settings_path

					div.col-md-9
						h1 
							= yield(:page_header)
						hr
						= yield

		= render 'layouts/slidebar'

app/views/layouts/application.html.slim
html
	= render 'layouts/head'
	body
		= render 'layouts/navbar'

		.sb-site
			= yield
			#spinner
				i.fa.fa-spinner.fa-2x.fa-spin

		= render 'layouts/slidebar'

app/views/layouts/application.mobile.slim
html
	head
	  title 
	  	= full_title(yield(:title))
	  meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui"
		link rel="stylesheet" href="//cdn.jsdelivr.net/ratchet/2.0.2/css/ratchet-theme-ios.min.css"
		link rel="stylesheet" href="//cdn.jsdelivr.net/ratchet/2.0.2/css/ratchet.min.css"
		script src="//cdn.jsdelivr.net/ratchet/2.0.2/js/ratchet.min.js"
		= stylesheet_link_tag  "mobile", media: "all", "data-turbolinks-track" => true 
		= javascript_include_tag "mobile"
		= csrf_meta_tags
		= favicon_link_tag 'favicon.ico'
	body
		header class="bar bar-nav"
			= yield :header
		.content
			= yield
		= render "shared/mobile_bar_tab"
		